import Day from './day-08';
import { dayRunner, dayVerifier } from './test-util';

const example = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`.trim();

dayRunner(Day, example, 14, 34);

dayVerifier(8, 289, 1030);
